import {useMemo,useRef,useState} from 'react';
import {
  ELECTROCHEMICAL_COUPLES,
  ELECTROCHEMICAL_DATA_NOTE,
  electrochemicalCoupleById,
} from '../data/electrochemicalCouples.js';
import {
  ELECTROCHEMICAL_MODEL_BOUNDARY,
  analyzeElectrochemicalCell,
  analyzeElectrolysis,
  createCellPotentialTrace,
  createDepositionTrace,
  evaluateCircuitPrediction,
  evaluateElectrolysisPrediction,
} from '../chemistry/electrochemistry.js';
import {MODEL_PASSPORTS,SCIENCE_SOURCES} from '../data/scienceSources.js';
import '../styles/electrochemistry.css';

const clamp=(value,minimum,maximum)=>Math.max(minimum,Math.min(maximum,value));
const compact=(value,digits=3)=>{
  if(!Number.isFinite(value))return '—';
  if(Math.abs(value)>=1e5||(Math.abs(value)>0&&Math.abs(value)<1e-3))return value.toExponential(2);
  return value.toFixed(digits);
};
const sideLabel=(side)=>side==='left'?'Left':'Right';

function CoupleDeck({side,selectedId,otherId,onChoose}){
  const selected=electrochemicalCoupleById(selectedId);
  return <aside className={`electro-couple-deck electro-card ${side}`}>
    <div className="electro-panel-heading"><span>{side} half-cell</span><strong>Choose one reduction couple</strong></div>
    <div className="electro-couple-options">{ELECTROCHEMICAL_COUPLES.map((couple)=><button type="button" key={couple.id} className={`${selectedId===couple.id?'active':''} ${otherId===couple.id?'paired':''}`} aria-pressed={selectedId===couple.id} onClick={()=>onChoose(side,couple.id)} style={{'--couple-accent':couple.accent,'--electrode':couple.electrodeColor}}><i/><span><b>{couple.ionLabel}/{couple.symbol}</b><strong>{couple.name}</strong><small>E° {couple.standardPotentialV>=0?'+':''}{couple.standardPotentialV.toFixed(4)} V</small></span>{otherId===couple.id&&<em>used opposite</em>}</button>)}</div>
    <div className="electro-selected-couple" style={{'--couple-accent':selected.accent,'--electrode':selected.electrodeColor,'--electrolyte':selected.electrolyteColor}}><div><i/><span>{selected.symbol}</span><b>{selected.ionLabel}</b></div><strong>{selected.reductionEquation}</strong><p>{selected.boundary}</p></div>
  </aside>;
}

function CircuitArrow({direction,className,marker}){
  const path=direction==='left-to-right'?'M190 78H710':'M710 78H190';
  return <path className={className} d={path} markerEnd={`url(#${marker})`}/>;
}

function CellTheatre({analysis,prediction,check}){
  const revealed=Boolean(check&&!check.blocked);
  const expected=analysis.spontaneous;
  const selected=analysis.selected;
  const meterAngle=revealed?clamp(selected.cellPotentialV/2.5,-1,1)*67:0;
  const modelElectronPath=expected.electronDirection==='left-to-right'?'M190 78H710':'M710 78H190';
  const cationPath=expected.cationDestination==='right'?'M410 270C450 160 500 160 540 270':'M540 270C500 160 450 160 410 270';
  const anionPath=expected.anionDestination==='right'?'M410 300C450 190 500 190 540 300':'M540 300C500 190 450 190 410 300';
  return <svg className={`electro-cell-svg ${revealed?'revealed':'waiting'} ${check?.correct?'correct':revealed?'compare':''}`} viewBox="0 0 900 545" role="img" aria-label={`Two-half-cell electrochemical switchboard. Left ${analysis.left.couple.name}, right ${analysis.right.couple.name}. ${revealed?`Selected orientation potential ${selected.cellPotentialV.toFixed(4)} volts. Model electrons move ${expected.electronDirection.replaceAll('-',' ')}.`:'Directions and voltage are concealed until all four predictions are checked.'}`}>
    <title>Split-glass electrochemical cell switchboard</title>
    <desc>The meter is an equilibrium open-circuit model. Electron and salt-bridge arrows are qualitative directions, not current or transport rates.</desc>
    <defs>
      <linearGradient id="electroGlass" x1="0" x2="1"><stop stopColor="#dff8ff" stopOpacity=".28"/><stop offset=".5" stopColor="#fff" stopOpacity=".08"/><stop offset="1" stopColor="#8ddff5" stopOpacity=".28"/></linearGradient>
      <linearGradient id="leftSolution" x1="0" y1="0" x2="0" y2="1"><stop stopColor={analysis.left.couple.electrolyteColor} stopOpacity=".6"/><stop offset="1" stopColor={analysis.left.couple.electrolyteColor} stopOpacity=".95"/></linearGradient>
      <linearGradient id="rightSolution" x1="0" y1="0" x2="0" y2="1"><stop stopColor={analysis.right.couple.electrolyteColor} stopOpacity=".6"/><stop offset="1" stopColor={analysis.right.couple.electrolyteColor} stopOpacity=".95"/></linearGradient>
      <linearGradient id="leftMetal" x1="0" x2="1"><stop stopColor="#fff"/><stop offset=".28" stopColor={analysis.left.couple.electrodeColor}/><stop offset="1" stopColor="#445162"/></linearGradient>
      <linearGradient id="rightMetal" x1="0" x2="1"><stop stopColor="#fff"/><stop offset=".28" stopColor={analysis.right.couple.electrodeColor}/><stop offset="1" stopColor="#445162"/></linearGradient>
      <filter id="electronGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
      <marker id="learnerCircuitArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#e87da3"/></marker>
      <marker id="modelCircuitArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#f6e37a"/></marker>
      <marker id="cationArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#7aa7ff"/></marker>
      <marker id="anionArrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#e87da3"/></marker>
    </defs>
    <g className="electro-grid">{Array.from({length:12},(_,index)=><line key={`v${index}`} x1={20+index*78} x2={20+index*78} y1="16" y2="525"/>)}{Array.from({length:8},(_,index)=><line key={`h${index}`} x1="15" x2="885" y1={24+index*70} y2={24+index*70}/>)}</g>
    <path className="circuit-wire" d="M190 270V78H350M550 78H710V270"/>
    {prediction.predictedElectronDirection&&<CircuitArrow direction={prediction.predictedElectronDirection} className="learner-circuit-arrow" marker="learnerCircuitArrow"/>}
    {revealed&&expected.electronDirection&&<><CircuitArrow direction={expected.electronDirection} className="model-circuit-arrow" marker="modelCircuitArrow"/>{[0,.34,.68].map((offset)=><circle key={offset} className="electron-pulse" r="6" filter="url(#electronGlow)"><animateMotion dur="2.2s" begin={`${-offset*2.2}s`} repeatCount="indefinite" path={modelElectronPath}/></circle>)}</>}
    <g className="electro-meter" transform="translate(450 95)"><circle r="102"/><path d="M-78 38A87 87 0 0 1 78 38"/><g className="meter-ticks">{[-70,-35,0,35,70].map((angle)=><line key={angle} x1="0" y1="-72" x2="0" y2="-84" transform={`rotate(${angle})`}/>)}</g><line className="meter-needle" x1="0" y1="11" x2="0" y2="-69" transform={`rotate(${meterAngle})`}/><circle r="9"/><text className="meter-value" y="47" textAnchor="middle">{revealed?`${selected.cellPotentialV>=0?'+':''}${selected.cellPotentialV.toFixed(4)} V`:'?'}</text><text className="meter-label" y="68" textAnchor="middle">equilibrium / open circuit</text><text className="meter-minus" x="-70" y="12">−</text><text className="meter-plus" x="65" y="12">+</text></g>
    <g className="left-vessel"><path className="vessel-glass" d="M76 190h240v278c0 25-20 45-45 45H121c-25 0-45-20-45-45z" fill="url(#electroGlass)"/><path className="solution" d="M86 306c40-15 75 10 110 0s69-12 110 0v158c0 21-17 37-37 37H123c-21 0-37-16-37-37z" fill="url(#leftSolution)"/><rect className="electrode" x="164" y="168" width="62" height="250" rx="8" fill="url(#leftMetal)"/><text className="electrode-symbol" x="195" y="225" textAnchor="middle">{analysis.left.couple.symbol}</text>{Array.from({length:9},(_,index)=><g key={index} className="solution-ion"><circle cx={110+(index%3)*78} cy={335+Math.floor(index/3)*56} r="16"/><text x={110+(index%3)*78} y={340+Math.floor(index/3)*56} textAnchor="middle">{analysis.left.couple.ionLabel}</text></g>)}<text className="activity-plaque" x="196" y="488" textAnchor="middle">a = {analysis.left.activity.toPrecision(3)}</text></g>
    <g className="right-vessel"><path className="vessel-glass" d="M584 190h240v278c0 25-20 45-45 45H629c-25 0-45-20-45-45z" fill="url(#electroGlass)"/><path className="solution" d="M594 306c40-15 75 10 110 0s69-12 110 0v158c0 21-17 37-37 37H631c-21 0-37-16-37-37z" fill="url(#rightSolution)"/><rect className="electrode" x="672" y="168" width="62" height="250" rx="8" fill="url(#rightMetal)"/><text className="electrode-symbol" x="703" y="225" textAnchor="middle">{analysis.right.couple.symbol}</text>{Array.from({length:9},(_,index)=><g key={index} className="solution-ion"><circle cx={618+(index%3)*78} cy={335+Math.floor(index/3)*56} r="16"/><text x={618+(index%3)*78} y={340+Math.floor(index/3)*56} textAnchor="middle">{analysis.right.couple.ionLabel}</text></g>)}<text className="activity-plaque" x="704" y="488" textAnchor="middle">a = {analysis.right.activity.toPrecision(3)}</text></g>
    <path className="salt-bridge-shell" d="M295 340V247c0-39 32-71 71-71h168c39 0 71 32 71 71v93"/>
    <path className="salt-bridge-core" d="M295 340V247c0-39 32-71 71-71h168c39 0 71 32 71 71v93"/>
    <g className="bridge-key" transform="translate(383 219)"><rect width="134" height="43" rx="12"/><text x="67" y="17" textAnchor="middle">SALT BRIDGE</text><text x="67" y="32" textAnchor="middle">ionic connection</text></g>
    {revealed&&expected.anodeSide&&<><path className="bridge-cation-arrow" d={cationPath} markerEnd="url(#cationArrow)"/><path className="bridge-anion-arrow" d={anionPath} markerEnd="url(#anionArrow)"/><g className="bridge-ion-labels"><text x="450" y="276" textAnchor="middle">K⁺ → {sideLabel(expected.cationDestination)}</text><text x="450" y="298" textAnchor="middle">NO₃⁻ → {sideLabel(expected.anionDestination)}</text></g></>}
    {revealed&&<><g className={`role-plaque left ${expected.anodeSide==='left'?'anode':'cathode'}`} transform="translate(87 118)"><rect width="218" height="47" rx="12"/><text x="12" y="19">{expected.anodeSide==='left'?'ANODE · OXIDATION':'CATHODE · REDUCTION'}</text><text x="12" y="36">{expected.anodeSide==='left'?analysis.selected.anodeSide==='left'?selected.oxidationEquation:'spontaneous direction':analysis.selected.cathodeSide==='left'?selected.reductionEquation:'spontaneous direction'}</text></g><g className={`role-plaque right ${expected.anodeSide==='right'?'anode':'cathode'}`} transform="translate(595 118)"><rect width="218" height="47" rx="12"/><text x="12" y="19">{expected.anodeSide==='right'?'ANODE · OXIDATION':'CATHODE · REDUCTION'}</text><text x="12" y="36">{expected.anodeSide==='right'?analysis.selected.anodeSide==='right'?selected.oxidationEquation:'spontaneous direction':analysis.selected.cathodeSide==='right'?selected.reductionEquation:'spontaneous direction'}</text></g></>}
    {!revealed&&<g className="cell-question"><circle cx="450" cy="334" r="45"/><text x="450" y="348" textAnchor="middle">?</text><text x="450" y="393" textAnchor="middle">commit four directions</text></g>}
    <text className="theatre-boundary" x="450" y="531" textAnchor="middle">qualitative flow only · potential is the zero-current equilibrium limit</text>
  </svg>;
}

function PotentialChart({trace,analysis,revealed}){
  const width=790,height=320,left=62,right=754,top=31,bottom=268;
  const values=trace.points.map((point)=>point.cellPotentialV);
  const min=Math.min(-.1,...values),max=Math.max(.1,...values);
  const x=(logQ)=>left+(logQ+8)/16*(right-left);
  const y=(potential)=>top+(max-potential)/(max-min)*(bottom-top);
  const path=trace.points.map((point,index)=>`${index?'L':'M'}${x(point.log10ReactionQuotient).toFixed(2)} ${y(point.cellPotentialV).toFixed(2)}`).join(' ');
  const currentLogQ=clamp(Math.log10(analysis.reactionQuotient),-8,8);
  return <svg className="electro-nernst-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Cell potential versus logarithm of reaction quotient for the learner-selected orientation. Current log Q ${Math.log10(analysis.reactionQuotient).toFixed(2)}. ${revealed?`Current potential ${analysis.cellPotentialV.toFixed(4)} volts.`:'Current potential concealed until predictions are checked.'}`}>
    <title>Nernst potential field</title><defs><linearGradient id="nernstLine" x1="0" x2="1"><stop stopColor="#54cbe8"/><stop offset=".5" stopColor="#f6e37a"/><stop offset="1" stopColor="#e87da3"/></linearGradient><filter id="nernstGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
    {[-8,-4,0,4,8].map((tick)=><g key={tick}><line className="nernst-grid vertical" x1={x(tick)} x2={x(tick)} y1={top} y2={bottom}/><text x={x(tick)} y={bottom+20} textAnchor="middle">{tick}</text></g>)}
    {[min,0,max].map((tick,index)=><g key={index}><line className={`nernst-grid ${tick===0?'zero':''}`} x1={left} x2={right} y1={y(tick)} y2={y(tick)}/><text x={left-9} y={y(tick)+4} textAnchor="end">{tick.toFixed(2)}</text></g>)}
    <path className="nernst-path" d={path}/><g className="standard-q-marker"><line x1={x(0)} x2={x(0)} y1={top} y2={bottom}/><text x={x(0)+6} y={top+13}>Q = 1</text></g>
    <g className="current-q-marker" filter="url(#nernstGlow)"><line x1={x(currentLogQ)} x2={x(currentLogQ)} y1={top} y2={bottom}/><circle cx={x(currentLogQ)} cy={y(analysis.cellPotentialV)} r="8"/><text x={x(currentLogQ)+10} y={y(analysis.cellPotentialV)-11}>{revealed?`${analysis.cellPotentialV.toFixed(3)} V`:'current Q'}</text></g>
    <text className="nernst-axis" x={(left+right)/2} y={height-10} textAnchor="middle">log₁₀ Q · selected reaction orientation</text><text className="nernst-axis" x="17" y={(top+bottom)/2} transform={`rotate(-90 17 ${(top+bottom)/2})`} textAnchor="middle">Ecell / V</text>
  </svg>;
}

function PredictionRow({label,detail,value,options,onChoose,tone}){
  return <div className={`electro-prediction-row ${tone??''}`}><span><strong>{label}</strong><small>{detail}</small></span><div>{options.map((option)=><button type="button" key={option.id} className={value===option.id?'selected':''} aria-pressed={value===option.id} onClick={()=>onChoose(option.id)}><b>{option.symbol}</b><span>{option.label}</span></button>)}</div></div>;
}

function DepositionChart({trace}){
  const width=680,height=260,left=57,right=653,top=28,bottom=213,max=Math.max(.001,trace.analysis.idealMassG*1.08);
  const x=(seconds)=>left+seconds/trace.analysis.input.timeSeconds*(right-left),y=(mass)=>top+(max-mass)/max*(bottom-top);
  const expectedPath=trace.points.map((point,index)=>`${index?'L':'M'}${x(point.timeSeconds).toFixed(2)} ${y(point.expectedMassG).toFixed(2)}`).join(' ');
  const idealPath=trace.points.map((point,index)=>`${index?'L':'M'}${x(point.timeSeconds).toFixed(2)} ${y(point.idealMassG).toFixed(2)}`).join(' ');
  return <svg className="electro-deposition-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Constant-current deposition trace. Ideal mass ${trace.analysis.idealMassG.toFixed(4)} grams; efficiency-adjusted mass ${trace.analysis.expectedMassG.toFixed(4)} grams after ${(trace.analysis.input.timeSeconds/60).toFixed(1)} minutes.`}><title>Ideal and efficiency-adjusted Faraday mass versus time</title>{[0,.25,.5,.75,1].map((fraction)=><g key={fraction}><line x1={left} x2={right} y1={y(max*fraction)} y2={y(max*fraction)}/><text x={left-8} y={y(max*fraction)+4} textAnchor="end">{(max*fraction).toFixed(2)}</text></g>)}<path className="deposit-ideal" d={idealPath}/><path className="deposit-expected" d={expectedPath}/><circle className="deposit-end" cx={x(trace.analysis.input.timeSeconds)} cy={y(trace.analysis.expectedMassG)} r="7"/><text className="deposit-label" x={right-4} y={y(trace.analysis.expectedMassG)-10} textAnchor="end">{trace.analysis.expectedMassG.toFixed(3)} g</text><text className="deposit-axis" x={(left+right)/2} y={height-9} textAnchor="middle">time / s · constant current and efficiency</text></svg>;
}

function PlatingTheatre({analysis,checked}){
  const depositThickness=6+clamp(analysis.expectedMassG/5,0,1)*34;
  return <svg className={`electro-plating-svg ${checked?'revealed':''}`} viewBox="0 0 560 410" role="img" aria-label={`Symbolic powered ${analysis.couple.name} deposition. ${analysis.input.currentA.toFixed(2)} amperes for ${(analysis.input.timeSeconds/60).toFixed(1)} minutes at ${(analysis.input.currentEfficiency*100).toFixed(0)} percent current efficiency. Deposit thickness is symbolic, not geometric prediction.`}><title>Powered ideal metal-deposition rail</title><defs><linearGradient id="platingBath" x1="0" y1="0" x2="0" y2="1"><stop stopColor={analysis.couple.electrolyteColor} stopOpacity=".55"/><stop offset="1" stopColor={analysis.couple.electrolyteColor}/></linearGradient><linearGradient id="platingMetal" x1="0" x2="1"><stop stopColor="#fff"/><stop offset=".35" stopColor={analysis.couple.electrodeColor}/><stop offset="1" stopColor="#354354"/></linearGradient><filter id="plateGlow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g className="power-supply"><rect x="174" y="22" width="212" height="95" rx="18"/><text x="280" y="50" textAnchor="middle">CONSTANT CURRENT</text><text className="power-value" x="280" y="83" textAnchor="middle">{analysis.input.currentA.toFixed(2)} A</text><circle cx="203" cy="95" r="8"/><text x="203" y="100" textAnchor="middle">+</text><circle cx="357" cy="95" r="8"/><text x="357" y="100" textAnchor="middle">−</text></g><path className="power-wire positive" d="M203 103V147H136v102"/><path className="power-wire negative" d="M357 103V147H424v102"/><path className="plating-vessel" d="M70 190h420v165c0 23-19 42-42 42H112c-23 0-42-19-42-42z"/><path className="plating-solution" d="M80 249c60-15 110 12 165 0s110-13 235 0v102c0 19-15 34-34 34H114c-19 0-34-15-34-34z" fill="url(#platingBath)"/><rect className="plate-electrode anode" x="108" y="169" width="56" height="176" rx="7" fill="url(#platingMetal)"/><rect className="plate-electrode cathode" x="396" y="169" width="56" height="176" rx="7" fill="#4b5665"/><rect className="deposit-layer" x={396-depositThickness} y="189" width={depositThickness} height="145" rx="7" fill="url(#platingMetal)" filter="url(#plateGlow)"/><text className="plate-symbol" x="136" y="221" textAnchor="middle">{analysis.couple.symbol}</text><text className="plate-symbol" x="424" y="221" textAnchor="middle">{analysis.couple.symbol}</text><text className="plate-role" x="136" y="370" textAnchor="middle">source electrode</text><text className="plate-role" x="424" y="370" textAnchor="middle">cathode · deposit</text>{Array.from({length:12},(_,index)=><g className="plating-ion" key={index}><circle cx={105+(index%6)*70} cy={275+Math.floor(index/6)*54} r="13"/><text x={105+(index%6)*70} y={279+Math.floor(index/6)*54} textAnchor="middle">{analysis.couple.ionLabel}</text></g>)}<text className="plate-boundary" x="280" y="405" textAnchor="middle">deposit edge is symbolic · no morphology, area, or product selection</text></svg>;
}

export default function ElectrochemistryLab(){
  const [leftCoupleId,setLeftCoupleId]=useState('zn');
  const [rightCoupleId,setRightCoupleId]=useState('cu');
  const [leftActivity,setLeftActivity]=useState(1);
  const [rightActivity,setRightActivity]=useState(1);
  const [temperatureK,setTemperatureK]=useState(298.15);
  const [prediction,setPrediction]=useState({predictedAnodeSide:null,predictedElectronDirection:null,predictedCationDestination:null,predictedAnionDestination:null});
  const [circuitCheck,setCircuitCheck]=useState(null);
  const [circuitFeedback,setCircuitFeedback]=useState({tone:'ready',title:'The switchboard is waiting.',detail:'Choose all four directions. The meter and model arrows stay hidden until you commit.'});
  const [platingCoupleId,setPlatingCoupleId]=useState('cu');
  const [currentA,setCurrentA]=useState(2);
  const [timeMinutes,setTimeMinutes]=useState(30);
  const [currentEfficiencyPercent,setCurrentEfficiencyPercent]=useState(100);
  const [predictedMass,setPredictedMass]=useState('');
  const [massCheck,setMassCheck]=useState(null);
  const [massFeedback,setMassFeedback]=useState({tone:'ready',title:'Predict the plated mass.',detail:'Build the charge ledger before revealing the efficiency-adjusted result.'});
  const [trace,setTrace]=useState([{id:0,type:'start',title:'Redox switchboard ready',detail:'Zn²⁺/Zn left · Cu²⁺/Cu right · all four direction predictions empty.'}]);
  const traceId=useRef(1);
  const record=(type,title,detail)=>{const id=traceId.current++;setTrace((current)=>[{id,type,title,detail},...current].slice(0,18));};

  const orientation=prediction.predictedAnodeSide==='right'?'right-oxidizes':'left-oxidizes';
  const analysis=useMemo(()=>analyzeElectrochemicalCell({leftCoupleId,rightCoupleId,leftActivity,rightActivity,temperatureK,orientation}),[leftCoupleId,rightCoupleId,leftActivity,rightActivity,temperatureK,orientation]);
  const potentialTrace=useMemo(()=>createCellPotentialTrace({leftCoupleId,rightCoupleId,temperatureK,orientation,pointCount:85}),[leftCoupleId,rightCoupleId,temperatureK,orientation]);
  const electrolysis=useMemo(()=>analyzeElectrolysis({coupleId:platingCoupleId,currentA,timeSeconds:timeMinutes*60,currentEfficiency:currentEfficiencyPercent/100}),[platingCoupleId,currentA,timeMinutes,currentEfficiencyPercent]);
  const depositionTrace=useMemo(()=>createDepositionTrace({coupleId:platingCoupleId,currentA,timeSeconds:timeMinutes*60,currentEfficiency:currentEfficiencyPercent/100,pointCount:45}),[platingCoupleId,currentA,timeMinutes,currentEfficiencyPercent]);
  const passport=MODEL_PASSPORTS.electrochemicalCell;
  const revealed=Boolean(circuitCheck&&!circuitCheck.blocked);

  const chooseCouple=(side,id)=>{
    const other=side==='left'?rightCoupleId:leftCoupleId;
    if(id===other){const couple=electrochemicalCoupleById(id);const detail=`${couple.name} is already used in the opposite half-cell. Choose a different declared couple; no half-cell changed.`;setCircuitFeedback({tone:'blocked',title:'Duplicate half-cell blocked.',detail});record('blocked','Duplicate half-cell blocked',detail);return;}
    if(side==='left')setLeftCoupleId(id);else setRightCoupleId(id);
    setCircuitCheck(null);const couple=electrochemicalCoupleById(id);const detail=`${sideLabel(side)} half-cell changed to ${couple.ionLabel}/${couple.symbol}. Existing direction choices remain visible but must be checked again.`;setCircuitFeedback({tone:'changed',title:`${couple.name} loaded on the ${side}.`,detail});record('setup','Half-cell changed',detail);
  };
  const choosePrediction=(key,value)=>{setPrediction((current)=>({...current,[key]:value}));setCircuitCheck(null);setCircuitFeedback({tone:'selected',title:'Direction choice recorded.',detail:'Complete all four predictions, then commit them together.'});};
  const parameterChanged=(title,detail)=>{setCircuitCheck(null);setCircuitFeedback({tone:'changed',title,detail:`${detail} Your four choices were preserved; check again when ready.`});};
  const checkCircuit=()=>{
    const missing=Object.entries(prediction).filter(([,value])=>!value).map(([key])=>key);
    if(missing.length){const detail=`${missing.length} ${missing.length===1?'direction is':'directions are'} still unselected. The model result remains hidden.`;setCircuitCheck({blocked:true});setCircuitFeedback({tone:'blocked',title:'Circuit check blocked.',detail});record('blocked','Circuit check blocked',detail);return;}
    const checked=evaluateCircuitPrediction({analysis,...prediction});setCircuitCheck(checked);setCircuitFeedback({tone:checked.correct?'correct':'incorrect',title:checked.correct?'All four directions match.':'Keep your choices and compare each direction.',detail:checked.summary});record(checked.correct?'correct':'incorrect','Circuit directions checked',checked.summary);
  };
  const resetDirections=()=>{setPrediction({predictedAnodeSide:null,predictedElectronDirection:null,predictedCationDestination:null,predictedAnionDestination:null});setCircuitCheck(null);const detail='All four learner directions were cleared. Half-cells, activities, and temperature were preserved.';setCircuitFeedback({tone:'ready',title:'Direction dock cleared.',detail});record('reset','Direction predictions cleared',detail);};
  const platingParameterChanged=(title,detail)=>{setMassCheck(null);setMassFeedback({tone:'changed',title,detail:`${detail} Your mass prediction was preserved for a new check.`});};
  const checkMass=()=>{const mass=Number(predictedMass);if(predictedMass===''||!Number.isFinite(mass)||mass<0){const detail='Enter a non-negative mass prediction in grams before revealing the Faraday result.';setMassCheck({blocked:true});setMassFeedback({tone:'blocked',title:'Mass check blocked.',detail});record('blocked','Electrolysis prediction blocked',detail);return;}const checked=evaluateElectrolysisPrediction({analysis:electrolysis,predictedMassG:mass,toleranceFraction:.03});setMassCheck(checked);setMassFeedback({tone:checked.correct?'correct':'incorrect',title:checked.correct?'Prediction is within 3%.':`Prediction is ${checked.classification}.`,detail:checked.reason});record(checked.correct?'correct':'incorrect','Plated-mass prediction checked',checked.reason);};

  const dimensionTone=(key)=>revealed?(circuitCheck.dimensions[key]?.correct?'correct':'incorrect'):'';
  return <section className="electrochemistry-lab" id="electrochemistryLab" aria-labelledby="electrochemistryLabTitle">
    <header className="electro-header"><div><p className="section-code">13 / Electrochemical cells</p><h2 id="electrochemistryLabTitle">Voltage is a chemical argument about direction—not a stream of electrons.</h2><p>Build two half-cells, commit every direction, then separate equilibrium potential from current and ideal Faraday yield from a real plating process.</p></div><div className="electro-header-instrument" aria-hidden="true"><div className="mini-cell left"><i/><b>Zn</b></div><span>e⁻</span><div className="mini-meter"><i/><b>V</b></div><span>e⁻</span><div className="mini-cell right"><i/><b>Cu</b></div><p>chemical → electrical</p></div></header>
    <div className="electro-bench">
      <CoupleDeck side="left" selectedId={leftCoupleId} otherId={rightCoupleId} onChoose={chooseCouple}/>
      <section className="electro-theatre electro-card"><div className="electro-stage-topline"><span><i/>redox switchboard · learner-wired</span><b>{analysis.resultKind}</b></div><CellTheatre analysis={analysis} prediction={prediction} check={circuitCheck}/><div className={`electro-stage-feedback ${circuitFeedback.tone}`} aria-live="polite"><i/><span><strong>{circuitFeedback.title}</strong><p>{circuitFeedback.detail}</p></span></div></section>
      <CoupleDeck side="right" selectedId={rightCoupleId} otherId={leftCoupleId} onChoose={chooseCouple}/>

      <aside className="electro-prediction-dock electro-card"><div className="electro-panel-heading"><span>Prediction dock</span><strong>Commit four directions together</strong></div>
        <PredictionRow label="Where is the anode?" detail="oxidation electrode" value={prediction.predictedAnodeSide} tone={dimensionTone('anode')} options={[{id:'left',label:`Left · ${analysis.left.couple.symbol}`,symbol:'L'},{id:'right',label:`Right · ${analysis.right.couple.symbol}`,symbol:'R'}]} onChoose={(value)=>choosePrediction('predictedAnodeSide',value)}/>
        <PredictionRow label="Where do electrons travel?" detail="external circuit" value={prediction.predictedElectronDirection} tone={dimensionTone('electrons')} options={[{id:'left-to-right',label:'Left → right',symbol:'→'},{id:'right-to-left',label:'Right → left',symbol:'←'}]} onChoose={(value)=>choosePrediction('predictedElectronDirection',value)}/>
        <PredictionRow label="Where do bridge cations migrate?" detail="positive bridge ions" value={prediction.predictedCationDestination} tone={dimensionTone('cations')} options={[{id:'left',label:'To left',symbol:'K⁺←'},{id:'right',label:'To right',symbol:'→K⁺'}]} onChoose={(value)=>choosePrediction('predictedCationDestination',value)}/>
        <PredictionRow label="Where do bridge anions migrate?" detail="negative bridge ions" value={prediction.predictedAnionDestination} tone={dimensionTone('anions')} options={[{id:'left',label:'To left',symbol:'NO₃⁻←'},{id:'right',label:'To right',symbol:'→NO₃⁻'}]} onChoose={(value)=>choosePrediction('predictedAnionDestination',value)}/>
        <div className="electro-prediction-actions"><button type="button" className="commit" onClick={checkCircuit}>Commit four directions <span aria-hidden="true">→</span></button><button type="button" onClick={resetDirections}>Clear directions</button></div>
        {revealed&&<div className="electro-dimension-reasons">{Object.entries(circuitCheck.dimensions).map(([key,dimension])=><p key={key} className={dimension.correct?'correct':'incorrect'}><i/><span><b>{key}</b>{dimension.reason}</span></p>)}</div>}
      </aside>

      <aside className={`electro-ledger electro-card ${revealed?analysis.selected.spontaneousAsWritten?'positive':'negative':'hidden'}`}><div className="electro-panel-heading"><span>Cell + energy ledger</span><strong>Your selected orientation stays intact</strong></div>{revealed?<><div className="electro-orientation-verdict"><span>As you wrote it</span><strong>{sideLabel(analysis.selected.anodeSide)} oxidizes · {analysis.selected.cellPotentialV>=0?'spontaneous':'nonspontaneous'} as written</strong><p>{analysis.selected.cellPotentialV>=0?'The selected oxidation/reduction direction has positive equilibrium potential.':'The negative sign is preserved. Reversing the chemical reaction would be the spontaneous orientation; this app did not reverse it for you.'}</p></div><div className="electro-reaction-stack"><div><span>Oxidation · anode</span><code>{analysis.oxidationEquation}</code></div><div><span>Reduction · cathode</span><code>{analysis.reductionEquation}</code></div><div className="overall"><span>Balanced cell reaction · n = {analysis.electronNumber}</span><code>{analysis.overallEquation}</code></div></div><dl className="electro-voltage-ledger"><div><dt>E°cell</dt><dd>{analysis.standardCellPotentialV>=0?'+':''}{analysis.standardCellPotentialV.toFixed(4)} V</dd></div><div><dt>Nernst subtraction</dt><dd>{analysis.nernstCorrectionV>=0?'+':''}{analysis.nernstCorrectionV.toFixed(5)} V</dd></div><div className="hero"><dt>Ecell</dt><dd>{analysis.cellPotentialV>=0?'+':''}{analysis.cellPotentialV.toFixed(4)} V</dd></div><div><dt>Q</dt><dd>{compact(analysis.reactionQuotient,3)}</dd></div><div><dt>ΔrG</dt><dd>{(analysis.deltaGJmol/1000).toFixed(2)} kJ mol⁻¹</dd></div><div><dt>log₁₀ K°</dt><dd>{analysis.log10StandardEquilibriumConstant.toFixed(2)}</dd></div></dl><div className="electro-cell-notation"><span>Cell notation · selected direction</span><code>{analysis.cellNotation}</code><small>Potential values are equilibrium/open-circuit model outputs, not voltage under load.</small></div><div className="electro-spontaneous-strip"><span>Spontaneous simple-cell direction</span><strong>{analysis.spontaneous.label}</strong><p>Electrons {analysis.spontaneous.electronDirection.replaceAll('-',' ')} · cations to {analysis.spontaneous.cationDestination} · anions to {analysis.spontaneous.anionDestination}</p></div></>:<div className="electro-ledger-lock"><i>V</i><strong>Meter and ledger concealed</strong><p>Use the half-reaction references and your activity choices. Commit all four directions to reveal the selected orientation and model comparison.</p></div>}</aside>

      <section className="electro-nernst electro-card"><div className="electro-panel-heading"><span>Activity-controlled Nernst field</span><strong>Composition can move the equilibrium potential</strong></div><div className="electro-nernst-layout"><div className="electro-activity-controls">
        {[{side:'left',couple:analysis.left.couple,value:leftActivity,setter:setLeftActivity},{side:'right',couple:analysis.right.couple,value:rightActivity,setter:setRightActivity}].map((item)=><label key={item.side}><span>{sideLabel(item.side)} activity · {item.couple.ionLabel}</span><strong>{item.value.toPrecision(3)}</strong><input aria-label={`${sideLabel(item.side)} ion activity logarithm`} type="range" min="-3" max="1" step="0.01" value={Math.log10(item.value)} onChange={(event)=>{item.setter(10**event.target.valueAsNumber);setCircuitCheck(null);}} onPointerUp={()=>parameterChanged(`${sideLabel(item.side)} activity changed`,`a(${item.couple.ionLabel}) = ${item.value.toPrecision(3)}.`)} onKeyUp={()=>parameterChanged(`${sideLabel(item.side)} activity changed`,`a(${item.couple.ionLabel}) = ${item.value.toPrecision(3)}.`)}/><input aria-label={`${sideLabel(item.side)} ion activity`} type="number" min="0.001" max="10" step="0.001" value={Number(item.value.toPrecision(6))} onChange={(event)=>{if(Number.isFinite(event.target.valueAsNumber)&&event.target.valueAsNumber>0){item.setter(clamp(event.target.valueAsNumber,.001,10));setCircuitCheck(null);}}} onBlur={()=>parameterChanged(`${sideLabel(item.side)} activity changed`,`a(${item.couple.ionLabel}) = ${item.value.toPrecision(3)}.`)}/><small>dimensionless · log₁₀ a = {Math.log10(item.value).toFixed(2)}</small></label>)}
        <label className="temperature"><span>Thermodynamic temperature</span><strong>{temperatureK.toFixed(2)} K</strong><input aria-label="Electrochemical cell temperature" type="range" min="273.15" max="373.15" step="0.05" value={temperatureK} onChange={(event)=>{setTemperatureK(event.target.valueAsNumber);setCircuitCheck(null);}} onPointerUp={()=>parameterChanged('Temperature changed',`T = ${temperatureK.toFixed(2)} K.`)} onKeyUp={()=>parameterChanged('Temperature changed',`T = ${temperatureK.toFixed(2)} K.`)}/><input aria-label="Electrochemical cell temperature numeric value" type="number" min="273.15" max="373.15" step="0.05" value={temperatureK} onChange={(event)=>{if(Number.isFinite(event.target.valueAsNumber)){setTemperatureK(clamp(event.target.valueAsNumber,273.15,373.15));setCircuitCheck(null);}}}/></label>
        <div className="electro-q-ledger"><span>Selected reaction quotient</span><code>Q = {analysis.reactionQuotientExpression}</code><strong>{compact(analysis.reactionQuotient,4)}</strong><p>Activities are learner inputs. No activity coefficient or concentration-to-activity conversion is inferred.</p></div>
      </div><div className="electro-nernst-chart-wrap"><PotentialChart trace={potentialTrace} analysis={analysis} revealed={revealed}/><div className="electro-chart-key"><span><i className="curve"/>Nernst line</span><span><i className="standard"/>Q = 1</span><span><i className="current"/>current Q</span></div><p><code>E = E° − (RT/nF) ln Q</code> · The selected reaction orientation defines Q and the sign of E.</p></div></div></section>

      <section className="electro-plating electro-card"><div className="electro-plating-heading"><div className="electro-panel-heading"><span>Powered Faraday rail</span><strong>Charge does not choose the product for you</strong></div><div className="plating-kind"><span>Separate model</span><strong>electrical → chemical</strong><small>constant current · learner-defined efficiency</small></div></div><div className="electro-plating-layout"><div className="plating-controls"><div className="plating-metal-deck"><span>Declared deposition reaction</span>{ELECTROCHEMICAL_COUPLES.filter((couple)=>['ag','cu','ni','zn'].includes(couple.id)).map((couple)=><button type="button" key={couple.id} className={platingCoupleId===couple.id?'active':''} aria-pressed={platingCoupleId===couple.id} onClick={()=>{setPlatingCoupleId(couple.id);setMassCheck(null);platingParameterChanged(`${couple.name} deposition selected`,couple.reductionEquation);}} style={{'--plate-accent':couple.electrodeColor}}><b>{couple.symbol}</b><span>{couple.ionLabel} + {couple.electronNumber}e⁻</span></button>)}</div>
        <label><span>Current</span><strong>{currentA.toFixed(2)} A</strong><input aria-label="Electrolysis current" type="range" min="0.1" max="10" step="0.05" value={currentA} onChange={(event)=>{setCurrentA(event.target.valueAsNumber);setMassCheck(null);}} onPointerUp={()=>platingParameterChanged('Current changed',`I = ${currentA.toFixed(2)} A.`)} onKeyUp={()=>platingParameterChanged('Current changed',`I = ${currentA.toFixed(2)} A.`)}/><input aria-label="Electrolysis current numeric value" type="number" min="0.1" max="10" step="0.05" value={currentA} onChange={(event)=>{if(Number.isFinite(event.target.valueAsNumber)){setCurrentA(clamp(event.target.valueAsNumber,.1,10));setMassCheck(null);}}} onBlur={()=>platingParameterChanged('Current changed',`I = ${currentA.toFixed(2)} A.`)}/></label>
        <label><span>Elapsed time</span><strong>{timeMinutes.toFixed(1)} min</strong><input aria-label="Electrolysis time" type="range" min="1" max="120" step="1" value={timeMinutes} onChange={(event)=>{setTimeMinutes(event.target.valueAsNumber);setMassCheck(null);}} onPointerUp={()=>platingParameterChanged('Time changed',`t = ${timeMinutes.toFixed(1)} min.`)} onKeyUp={()=>platingParameterChanged('Time changed',`t = ${timeMinutes.toFixed(1)} min.`)}/><input aria-label="Electrolysis time numeric value" type="number" min="1" max="120" step="1" value={timeMinutes} onChange={(event)=>{if(Number.isFinite(event.target.valueAsNumber)){setTimeMinutes(clamp(event.target.valueAsNumber,1,120));setMassCheck(null);}}} onBlur={()=>platingParameterChanged('Time changed',`t = ${timeMinutes.toFixed(1)} min.`)}/></label>
        <label><span>Current efficiency</span><strong>{currentEfficiencyPercent.toFixed(0)}%</strong><input aria-label="Deposition current efficiency" type="range" min="50" max="100" step="1" value={currentEfficiencyPercent} onChange={(event)=>{setCurrentEfficiencyPercent(event.target.valueAsNumber);setMassCheck(null);}} onPointerUp={()=>platingParameterChanged('Current efficiency changed',`ε = ${currentEfficiencyPercent.toFixed(0)}%.`)} onKeyUp={()=>platingParameterChanged('Current efficiency changed',`ε = ${currentEfficiencyPercent.toFixed(0)}%.`)}/><input aria-label="Deposition current efficiency numeric value" type="number" min="50" max="100" step="1" value={currentEfficiencyPercent} onChange={(event)=>{if(Number.isFinite(event.target.valueAsNumber)){setCurrentEfficiencyPercent(clamp(event.target.valueAsNumber,50,100));setMassCheck(null);}}} onBlur={()=>platingParameterChanged('Current efficiency changed',`ε = ${currentEfficiencyPercent.toFixed(0)}%.`)}/></label>
        <div className="plating-prediction"><label htmlFor="predictedPlateMass"><span>Your deposited-mass prediction</span><input id="predictedPlateMass" aria-label="Predicted deposited mass" type="number" min="0" step="0.001" placeholder="grams" value={predictedMass} onChange={(event)=>{setPredictedMass(event.target.value);setMassCheck(null);}}/><b>g</b></label><button type="button" onClick={checkMass}>Check mass prediction <span aria-hidden="true">→</span></button></div>
        <div className={`plating-feedback ${massFeedback.tone}`} aria-live="polite"><i/><span><strong>{massFeedback.title}</strong><p>{massFeedback.detail}</p></span></div>
      </div><div className="plating-theatre-wrap"><PlatingTheatre analysis={electrolysis} checked={Boolean(massCheck&&!massCheck.blocked)}/><p>{electrolysis.boundary}</p></div><div className="plating-ledger"><div className="electro-panel-heading"><span>Charge-to-mass ledger</span><strong>{massCheck&&!massCheck.blocked?`${electrolysis.expectedMassG.toFixed(5)} g`:'result concealed'}</strong></div><div className="charge-rail"><div><span>1 · charge</span><strong>{massCheck&&!massCheck.blocked?`${electrolysis.chargeC.toFixed(1)} C`:'I × t'}</strong><small>{currentA.toFixed(2)} A × {(timeMinutes*60).toFixed(0)} s</small></div><i>→</i><div><span>2 · electrons</span><strong>{massCheck&&!massCheck.blocked?`${electrolysis.electronAmountMol.toExponential(3)} mol`:'Q / F'}</strong><small>F = 96485.33212 C mol⁻¹</small></div><i>→</i><div><span>3 · ideal metal</span><strong>{massCheck&&!massCheck.blocked?`${electrolysis.idealDepositAmountMol.toExponential(3)} mol`:'mol e⁻ / z'}</strong><small>z = {electrolysis.electronNumber}</small></div><i>→</i><div><span>4 · adjusted mass</span><strong>{massCheck&&!massCheck.blocked?`${electrolysis.expectedMassG.toFixed(5)} g`:'× M × ε'}</strong><small>ideal {electrolysis.idealMassG.toFixed(5)} g · ε {currentEfficiencyPercent}%</small></div></div><DepositionChart trace={depositionTrace}/>{massCheck&&!massCheck.blocked&&<div className={`mass-comparison ${massCheck.correct?'correct':'incorrect'}`}><div><span>Your prediction</span><strong>{massCheck.predictedMassG.toFixed(5)} g</strong></div><i>vs</i><div><span>Model result</span><strong>{massCheck.expectedMassG.toFixed(5)} g</strong></div><p>{massCheck.reason}</p></div>}<p className="plating-equation"><code>{electrolysis.equation}</code> · Current efficiency is an input describing the charge fraction assigned to this declared product; it is not predicted.</p></div></div></section>

      <aside className="electro-learning-trace electro-card"><div className="electro-panel-heading"><span>Learner-owned trace</span><strong>Predictions and revisions stay visible</strong></div><div className="electro-attempts">{trace.map((entry)=><div key={entry.id} className={entry.type}><i/><span>{entry.type}</span><strong>{entry.title}</strong><p>{entry.detail}</p></div>)}</div><details className="electro-teacher-lens"><summary>Teacher lens · questions that expose the model</summary><div><p><b>Potential ≠ current:</b> Ask what additional information is needed to predict amperes after the circuit closes.</p><p><b>Thermodynamics ≠ kinetics:</b> Ask why positive E does not specify reaction rate or electrode overpotential.</p><p><b>Activity ≠ concentration:</b> Ask what activity coefficients would be needed for a real electrolyte.</p><p><b>Faraday yield ≠ product selection:</b> Ask why current efficiency must be supplied rather than inferred here.</p></div></details></aside>

      <aside className="electro-passport electro-card"><div className="electro-passport-intro"><div className="electro-panel-heading"><span>Equilibrium + electrolysis passport</span><strong>{passport.name}</strong></div><div className="electro-passport-verdict"><i/>{passport.resultKind}</div><p>{passport.inputProvenance}</p></div><div className="electro-passport-groups"><div><span>Included</span>{ELECTROCHEMICAL_MODEL_BOUNDARY.includes.map((item)=><b key={item}>{item}</b>)}</div><div className="excluded"><span>Not included</span>{ELECTROCHEMICAL_MODEL_BOUNDARY.excludes.map((item)=><b key={item}>{item}</b>)}</div></div><div className="electro-passport-equations"><span>Declared relations</span><code>E = E° − (RT/nF) ln Q</code><code>ΔrG = −nFE</code><code>ln K° = nFE°/(RT)</code><code>m = MItε/(zF)</code><p>{passport.dataStatement}</p><small>{ELECTROCHEMICAL_DATA_NOTE}</small></div><div className="electro-sources"><span>Primary references</span>{passport.sources.map((sourceId)=>{const source=SCIENCE_SOURCES[sourceId];return <a key={source.id} href={source.url} target="_blank" rel="noreferrer"><strong>{source.name}</strong><small>{source.role}</small><b aria-hidden="true">↗</b></a>;})}</div></aside>
    </div>
  </section>;
}
