import {useMemo,useState} from 'react';
import {MECHANISM_SCENARIOS} from '../data/mechanismScenarios.js';
import {commitElectronFlow,evaluateElectronArrow,nextElectronFlowHint} from '../chemistry/electronFlow.js';
import {MODEL_PASSPORTS,SCIENCE_SOURCES} from '../data/scienceSources.js';

let mechanismActivityId=0;
function activity(kind,title,detail){mechanismActivityId+=1;return{id:mechanismActivityId,kind,title,detail};}
function keyActivate(event,callback){if(event.key==='Enter'||event.key===' '){event.preventDefault();callback();}}

function BondGraphic({bond,atoms}){
  const a=atoms.get(bond.a),b=atoms.get(bond.b);if(!a||!b)return null;
  const dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1,nx=-dy/length,ny=dx/length;
  const offsets=bond.order===1?[0]:bond.order===2?[-5,5]:[-8,0,8];
  return <g className={`mechanism-bond ${bond.polar?'polar':''} ${bond.geometry?'geometry':''}`}>{offsets.map((offset,index)=><line key={index} x1={a.x+nx*offset} y1={a.y+ny*offset} x2={b.x+nx*offset} y2={b.y+ny*offset}/>)}</g>;
}

function queuedArrowPath(source,target,index){
  const dx=target.x-source.x,dy=target.y-source.y,distance=Math.max(80,Math.hypot(dx,dy));
  const nx=-dy/distance,ny=dx/distance,bend=(index%2===0?1:-1)*Math.min(105,55+distance*.09);
  const c1x=source.x+dx*.28+nx*bend,c1y=source.y+dy*.28+ny*bend,c2x=source.x+dx*.72+nx*bend,c2y=source.y+dy*.72+ny*bend;
  return {d:`M ${source.x} ${source.y} C ${c1x} ${c1y}, ${c2x} ${c2y}, ${target.x} ${target.y}`,labelX:(source.x+target.x)/2+nx*bend*.7,labelY:(source.y+target.y)/2+ny*bend*.7};
}

function MechanismCanvas({scenario,queuedArrows,selectedSource,onSource,onTarget}){
  const atoms=useMemo(()=>new Map(scenario.atoms.map((atom)=>[atom.id,atom])),[scenario]);
  const sourceMap=useMemo(()=>new Map(scenario.sources.map((source)=>[source.id,source])),[scenario]);
  const targetMap=useMemo(()=>new Map(scenario.targets.map((target)=>[target.id,target])),[scenario]);
  return <div className="mechanism-canvas-wrap"><svg className="mechanism-canvas" viewBox="0 0 900 500" role="img" aria-label={`${scenario.title}. Select an electron source, then a destination. ${queuedArrows.length} of ${scenario.arrowCount} arrows queued.`}>
    <title>{scenario.title}</title><desc>{scenario.learningOutcome} Product remains locked until the complete simultaneous arrow set is committed.</desc>
    <defs><marker id="mechanismArrowHead" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0,0 L10,5 L0,10 Z" fill="#ffd166"/></marker><filter id="mechanismGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
    <g className="mechanism-grid">{[100,200,300,400,500,600,700,800].map((x)=><line key={`x${x}`} x1={x} x2={x} y1="45" y2="455"/>)}{[100,200,300,400].map((y)=><line key={`y${y}`} x1="45" x2="855" y1={y} y2={y}/>)}</g>
    <g className="mechanism-bonds">{scenario.bonds.map((bond)=><BondGraphic key={bond.id} bond={bond} atoms={atoms}/>)}</g>
    <g className="mechanism-atoms">{scenario.atoms.map((atom)=><g key={atom.id} className={`mechanism-atom ${atom.tone||''} ${atom.element==='group'?'group':''}`} transform={`translate(${atom.x} ${atom.y})`}><circle r={atom.element==='group'?29:34}/><text textAnchor="middle" y="7">{atom.label}</text>{atom.charge!==undefined&&atom.charge!==0&&<text className="atom-charge" x="26" y="-24">{atom.charge>0?'+':'−'}</text>}{atom.partialCharge&&<text className="partial-charge" x="28" y="-25">{atom.partialCharge}</text>}</g>)}</g>
    <g className="queued-curly-arrows">{queuedArrows.map((queued,index)=>{const source=sourceMap.get(queued.sourceId),target=targetMap.get(queued.targetId),path=queuedArrowPath(source,target,index);return <g key={`${queued.sourceId}-${queued.targetId}`}><path className="curly-arrow-shadow" d={path.d}/><path className="curly-arrow" d={path.d} markerEnd="url(#mechanismArrowHead)"/><text className="curly-arrow-label" x={path.labelX} y={path.labelY} textAnchor="middle">2e⁻</text></g>;})}</g>
    <g className="electron-sources">{scenario.sources.map((source)=>{const queued=queuedArrows.some((arrow)=>arrow.sourceId===source.id),selected=selectedSource===source.id;return <g key={source.id} role="button" tabIndex={0} aria-label={`Select electron source: ${source.label}`} className={`electron-source ${source.type} ${queued?'queued':''} ${selected?'selected':''}`} transform={`translate(${source.x} ${source.y})`} onClick={()=>onSource(source)} onKeyDown={(event)=>keyActivate(event,()=>onSource(source))}><circle className="source-halo" r="27"/><circle className="electron one" cx="-5" r="4"/><circle className="electron two" cx="5" r="4"/><text y="43" textAnchor="middle">{source.type==='lonePair'?'lone pair':source.type==='piBond'?'π pair':'σ pair'}</text></g>;})}</g>
    <g className="electron-targets">{scenario.targets.map((target)=>{const active=Boolean(selectedSource);return <g key={target.id} role="button" tabIndex={0} aria-label={`Choose electron destination: ${target.label}`} className={`electron-target ${active?'active':''}`} transform={`translate(${target.x} ${target.y})`} onClick={()=>onTarget(target)} onKeyDown={(event)=>keyActivate(event,()=>onTarget(target))}><circle r="44"/><path d="M-9 0 H9 M0 -9 V9"/><text y="58" textAnchor="middle">{target.type==='bond'?'bond sink':'atom sink'}</text></g>;})}</g>
    {scenario.id==='e2-elimination'&&<g className="anti-geometry"><line x1="420" y1="70" x2="745" y2="250"/><text x="585" y="115" textAnchor="middle">template supplies antiperiplanar H–C–C–Br</text></g>}
    <text className="mechanism-axis-label" x="450" y="480" textAnchor="middle">electron-pair map · reactant representation</text>
  </svg><div className="mechanism-legend"><span><i className="source"/>electron-pair tail</span><span><i className="target"/>possible arrow head</span><span><i className="arrow"/>learner-queued 2e⁻ arrow</span></div></div>;
}

function ProductPanel({scenario,result}){
  if(!result?.committed)return <section className="mechanism-product locked"><div className="product-lock-graphic"><i/><i/><i/></div><div><span>Product locked</span><h3>Commit the complete simultaneous arrow set.</h3><p>The studio will not infer, add, or repair a missing companion arrow.</p></div></section>;
  return <section className="mechanism-product revealed"><div className="product-success-mark"><span>{scenario.shortName}</span><i/><i/></div><div className="product-copy"><span>Formal product representation revealed</span><h3>{result.product.notation}</h3><p>{result.product.summary}</p><div className="electron-conservation"><strong>{result.totalArrows} arrows</strong><i>×</i><strong>2 electrons</strong><i>=</i><strong>{result.electronsMoved} electrons moved</strong></div></div><div className="product-ledger"><span>Bond and charge ledger</span>{result.ledger.map((entry,index)=><div key={`${entry.kind}-${index}`} className={entry.kind}><i/>{entry.text}</div>)}</div><p className="product-boundary">{result.modelBoundary}</p></section>;
}

export default function MechanismLab(){
  const [scenarioId,setScenarioId]=useState('sn2-substitution'),[queuedArrows,setQueuedArrows]=useState([]),[selectedSource,setSelectedSource]=useState(null),[result,setResult]=useState(null),[hintLevel,setHintLevel]=useState(0),[feedback,setFeedback]=useState({kind:'ready',title:'Choose an electron pair',detail:'Every curly-arrow tail must begin at a lone pair or bond pair.'}),[attempts,setAttempts]=useState([activity('load','SN2 template loaded','No arrows are queued. The product is locked.')]);
  const scenario=MECHANISM_SCENARIOS.find((candidate)=>candidate.id===scenarioId)||MECHANISM_SCENARIOS[0],passport=MODEL_PASSPORTS.electronFlow;
  const addAttempt=(kind,title,detail)=>setAttempts((current)=>[activity(kind,title,detail),...current].slice(0,14));
  const chooseScenario=(next)=>{setScenarioId(next.id);setQueuedArrows([]);setSelectedSource(null);setResult(null);setHintLevel(0);setFeedback({kind:'ready',title:'Choose an electron pair',detail:next.learningOutcome});setAttempts([activity('load',`${next.shortName} template loaded`,'Arrow queue and product state were cleared explicitly.')]);};
  const chooseSource=(source)=>{setSelectedSource(source.id);setFeedback({kind:'source',title:`Tail selected: ${source.label}`,detail:'Now choose the atom or bond region where this same electron pair goes.'});};
  const chooseTarget=(target)=>{
    if(!selectedSource){const detail='Choose a glowing electron-pair tail before choosing an arrow head.';setFeedback({kind:'blocked',title:'No electron origin selected',detail});addAttempt('blocked','Destination rejected',detail);return;}
    const evaluation=evaluateElectronArrow(scenario.id,selectedSource,target.id,queuedArrows);
    if(!evaluation.allowed){setFeedback({kind:'blocked',title:'Arrow blocked',detail:evaluation.reason});addAttempt('blocked','Arrow blocked',evaluation.reason);return;}
    setQueuedArrows(evaluation.queue);setSelectedSource(null);setResult(null);setHintLevel(0);setFeedback({kind:'allowed',title:evaluation.arrow.role,detail:evaluation.reason});addAttempt('allowed','Two-electron arrow queued',`${evaluation.arrow.source.label} → ${evaluation.arrow.target.label}. ${evaluation.arrow.effect}`);
  };
  const removeArrow=(arrow)=>{const expected=scenario.expectedArrows.find((candidate)=>candidate.sourceId===arrow.sourceId&&candidate.targetId===arrow.targetId);setQueuedArrows((current)=>current.filter((candidate)=>!(candidate.sourceId===arrow.sourceId&&candidate.targetId===arrow.targetId)));setResult(null);setHintLevel(0);setFeedback({kind:'ready',title:'Arrow removed',detail:'Only the selected arrow was removed. Choose another electron pair or commit the remaining queue.'});addAttempt('remove','Arrow removed',expected?.role||`${arrow.sourceId} → ${arrow.targetId}`);};
  const clearArrows=()=>{setQueuedArrows([]);setSelectedSource(null);setResult(null);setHintLevel(0);setFeedback({kind:'ready',title:'Arrow queue cleared',detail:'The reactant template is unchanged and the product is locked.'});addAttempt('reset','All queued arrows cleared','No chemical state was repaired or completed automatically.');};
  const commit=()=>{const evaluation=commitElectronFlow(scenario.id,queuedArrows);if(!evaluation.committed){setFeedback({kind:'blocked',title:`Commit blocked · ${evaluation.missing?.length||0} arrow${evaluation.missing?.length===1?'':'s'} missing`,detail:evaluation.reason});addAttempt('incomplete','Elementary step not committed',evaluation.reason);return;}setResult(evaluation);setSelectedSource(null);setFeedback({kind:'success',title:evaluation.product.title,detail:`${evaluation.electronsMoved} electrons are accounted for across ${evaluation.totalArrows} learner-selected arrows.`});addAttempt('success','Elementary step committed',`${evaluation.product.notation}. ${evaluation.reason}`);};
  const showHint=()=>{const next=Math.min(3,hintLevel+1),hint=nextElectronFlowHint(scenario.id,queuedArrows,next);setHintLevel(next);setFeedback({kind:'hint',title:`Hint ${hint.level||'complete'}`,detail:hint.text});addAttempt('hint',`Hint ${hint.level||'complete'} opened`,hint.text);};
  const queuedDetails=queuedArrows.map((arrow)=>{const expected=scenario.expectedArrows.find((candidate)=>candidate.sourceId===arrow.sourceId&&candidate.targetId===arrow.targetId),source=scenario.sources.find((candidate)=>candidate.id===arrow.sourceId),target=scenario.targets.find((candidate)=>candidate.id===arrow.targetId);return{...arrow,expected,source,target};});
  return <section className="mechanism-lab" id="mechanismLab" aria-labelledby="mechanismLabTitle"><header className="mechanism-header"><div><p className="section-code">25 / Organic electron flow</p><h2 id="mechanismLabTitle">Arrows do not start at atoms. They start at electrons.</h2><p>Pick an electron pair, choose where it goes, and commit every simultaneous move yourself. Wrong attempts preserve the drawing and explain the formal reason.</p></div><div className="mechanism-condition-stamp"><span>Manual notation engine</span><strong>Four bounded two-electron templates</strong><small>No automatic companion arrows · no product prediction</small></div></header>
    <div className="mechanism-bench">
      <aside className="scenario-rail"><div className="mechanism-panel-heading"><span>Elementary-step library</span><strong>Choose one formal problem</strong></div>{MECHANISM_SCENARIOS.map((item)=><button type="button" key={item.id} className={item.id===scenario.id?'active':''} onClick={()=>chooseScenario(item)}><span>{item.shortName}</span><div><strong>{item.family}</strong><small>{item.title}</small></div><b>{item.arrowCount} arrows</b></button>)}<div className="scenario-contract"><span>Interaction contract</span><ol><li><i>1</i>Select an electron pair.</li><li><i>2</i>Select its destination.</li><li><i>3</i>Commit all arrows together.</li></ol></div><div className="scenario-boundary"><span>Template boundary</span><p>{scenario.boundary}</p></div></aside>

      <section className="mechanism-stage"><div className="mechanism-stage-topline"><span><i/>reactant electron map</span><b>{scenario.equation}</b></div><MechanismCanvas scenario={scenario} queuedArrows={queuedArrows} selectedSource={selectedSource} onSource={chooseSource} onTarget={chooseTarget}/></section>

      <aside className="mechanism-workflow"><div className="mechanism-panel-heading"><span>Arrow queue</span><strong>{queuedArrows.length} of {scenario.arrowCount} required</strong></div><div className="arrow-progress"><i style={{width:`${queuedArrows.length/scenario.arrowCount*100}%`}}/></div><div className={`mechanism-feedback ${feedback.kind}`} aria-live="polite"><span>{feedback.title}</span><p>{feedback.detail}</p></div><div className="arrow-queue">{queuedDetails.length?queuedDetails.map((arrow,index)=><div key={`${arrow.sourceId}-${arrow.targetId}`}><span>{String(index+1).padStart(2,'0')} · 2e⁻</span><strong>{arrow.source.label} → {arrow.target.label}</strong><p>{arrow.expected.role}</p><button type="button" onClick={()=>removeArrow(arrow)}>Remove this arrow</button></div>):<p className="empty-arrow-queue">No arrows queued. The product will remain locked.</p>}</div><div className="mechanism-actions"><button type="button" className="btn ghost" disabled={!queuedArrows.length} onClick={clearArrows}>Clear arrows</button><button type="button" className="btn primary" onClick={commit}>Commit elementary step</button></div><button type="button" className="hint-button" onClick={showHint}>Show {hintLevel<3?`hint ${hintLevel+1}`:'full hint again'}</button><p className="simultaneous-note"><strong>Why simultaneous?</strong>{scenario.simultaneousReason}</p></aside>

      <ProductPanel scenario={scenario} result={result}/>

      <aside className="mechanism-trace"><div className="mechanism-panel-heading"><span>Electron ledger</span><strong>Every attempt stays visible</strong></div><div className="mechanism-attempts">{attempts.map((entry)=><div className={entry.kind} key={entry.id}><i/><span>{entry.kind}</span><strong>{entry.title}</strong><p>{entry.detail}</p></div>)}</div></aside>

      <aside className="mechanism-passport"><div className="mechanism-panel-heading"><span>Model passport</span><strong>{passport.name}</strong></div><div className="mechanism-passport-verdict"><i/>{passport.resultKind}</div><p>{passport.inputProvenance}</p><div className="mechanism-passport-group"><span>Included</span><div>{passport.includes.map((item)=><b key={item}>{item}</b>)}</div></div><div className="mechanism-passport-group excluded"><span>Not included</span><div>{passport.excludes.map((item)=><b key={item}>{item}</b>)}</div></div><p>{passport.dataStatement}</p><div className="mechanism-equations"><span>Notation rules in use</span><code>curly-arrow tail = electron-pair origin</code><code>curly-arrow head = electron-pair destination</code><code>1 full arrow = 2 electrons</code></div><div className="mechanism-sources"><span>Reference basis</span>{passport.sources.map((sourceId)=>{const source=SCIENCE_SOURCES[sourceId];return<a key={source.id} href={source.url} target="_blank" rel="noreferrer"><strong>{source.name}</strong><small>{source.role}</small><b aria-hidden="true">↗</b></a>;})}</div></aside>
    </div>
  </section>;
}
